### ISSUE TITLE
M4 theta method (question)

### ISSUE THREAD

**Issue by skw1990** [M4Competition/M4-methods#1]
Hi, 

Came across this topic when searching for existing forecast tool.
In respect to the method shown, is there any reference on the theta model exhibited? (i.e.: logic of the codes)

Much appreciated.

**Comment by M4Competition** [comment]
Sure. You may first have a look at the original paper of _Assimakopoulos & Nikolopoulos, 2000. The theta model: a decomposition approach to forecasting. International Journal of Forecasting, 16 (4), 521-530._ 
It is available here:
https://www.sciencedirect.com/science/article/pii/S0169207000000662

The paper of Fiorucci et al., should also help you understand the principles of Theta. 
https://www.sciencedirect.com/science/article/pii/S0169207016300243

**Comment by skw1990** [comment]
That's helpful. Before I proceed to drill down on the technical details, may I know if the "**4**" in method here (since it's coined as _4theta_) symbolizes anything, with respect to either of the papers. 

Thanks for answering my queries in advance. =)

**Comment by M4Competition** [comment]
Theta and 4Theta are actually two different methods. The former, as described in the first paper provided, is used as a benchmark in M4 as it was the best performing method of the previous forecasting Competition (M3). The latter is a submission made by Forecasting & Strategy Unit (NTUA). 

4Theta has not been published yet, but some of the ideas utilised by the method are described here:
https://www.sciencedirect.com/science/article/pii/S0925527318300501

In brief, 4Theta uses the basic principles of Theta, but instead of considering only linear trends, it also utilises non-linear trends, as well as multiplicative and additive expressions of the original method. Thus, 4Theta generalises Theta and enables flexible, automatic forecasting.

**Comment by Arsa-Nik** [comment]
It seems 'mean' is missing in smape_cal function in Benchmarks and Evaluation code.

**Comment by Arsa-Nik** [comment]
Hi,

1) Do we need to constrain forecast values and Prediction intervals to stay (>=0)? I couldn't  find any guidance or rule regarding that.
2) mean() function is missing in your smape_cal function.

Thanks,
Arsa

**Comment by M4Competition** [comment]
Dear Arsa,

1. You are not obliged to constrain forecasts to stay positive. Yet, it
could be quite a reasonable approach given that the historical data are
positive. For instance, the Theta method (M4 benchmark) used such a
constrain for the case of the M3 Competition. It's up to you.

2. It's not missing. The function is actually used for estimating sAPE for
all the forecasts individually. Then, you can average these values to get
sMAPE, as done at the end of the script provided.

Hope that helps,
Vangelis

2018-05-09 15:44 GMT+03:00 Arsa-Nik <notifications@github.com>:
