### ISSUE TITLE
Benchmarks naive_seasonal

### ISSUE THREAD

**Issue by oleksastepaniuk** [M4Competition/M4-methods#21]
In the file 'Benchmarks and Evaluation.R', function naive_seasonal, line 43, is ''+ frcst - frcst" actually meaningful? It seems that it does nothing

**Comment by M4Competition** [comment]
Thanks for mentioning that. The answer is no, it isn't really meaningful.
What it does is the following:
- When you estimate || head(rep(as.numeric(tail(input,frcy)), fh), fh) || the results is a vector, not a time series object. So you have to specify its starting and end period
- On the other hand || frcst <- naive(input, h=fh)$mean || does that automatically as the naive() function returns this information
- So, instead of setting the start-end time manually, the || + frcst - frcst || is used as a "trick" to pass this info to the vector as well
To conclude, || + frcst - frcst ||  could be committed as long as the start-end period of the frcst variable was specified.

**Comment by oleksastepaniuk** [comment]
Thank you! Now I see that it makes sense
