### ISSUE TITLE
Potential security issues: SIOPREDM4.exe

### ISSUE THREAD

**Issue by PatrickTranekaerHansen** [M4Competition/M4-methods#23]
Sorry if this is a false alarm, but my antivirus just reacted to
SIOPREDM4.exe

**Comment by M4Competition** [comment]
Thank you for reporting this issue. 
Unfortunately, when we first scanned the file (some months ago) no threats were detected. It seems that updated antivirus software can now detect some possible threats.
Thus, we added a warning message so that anyone interested in downloading the file does this on its own responsibility.
